server:
  port: 8081
  servlet:
    contextPath: /users

spring:
  application:
    name: user-service

---
spring:
  config:
    activate:
      on-profile: default
    import: configserver:http://localhost:8888

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

